security:
  secret-key: is2-secretkey
server:
  port: 8080
spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, auditevents
  metrics:
    export:
      atlas:
        enabled: false
logging:
  file:
    name: logs/api-gateway.log
    max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{transaction.id}  %-5level %logger{36} \\(%line\\) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{transaction.id}  %-5level %logger{36} \\(%line\\) - %msg%n"
  level:
    org.springframework.web: OFF
    org.hibernate: ERROR
    it.almaviva.gestbeni: INFO
