server:
  port: 0
spring:
  profiles:
    active: dev
  application:
    name: sample-backend
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

functions:
  sampleQueueName: sampleQueue.sampleQueue-group

logging:
  file:
    name: logs/sample-backend.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{transaction.id}  %-5level %logger{36} \\(%line\\) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %X{transaction.id}  %-5level %logger{36} \\(%line\\) - %msg%n"
  level:
    org.springframework.web: OFF
    org.hibernate: ERROR
    it.almaviva.gestbeni: INFO
